from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.button0 = QtWidgets.QPushButton(self.centralwidget)
        self.button0.setGeometry(QtCore.QRect(0, 320, 80, 80))
        self.button0.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.button0.setObjectName("button0")
        self.button_equal = QtWidgets.QPushButton(self.centralwidget)
        self.button_equal.setGeometry(QtCore.QRect(220, 320, 80, 80))
        self.button_equal.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(255, 255, 255);")
        self.button_equal.setObjectName("button_equal")
        self.button7 = QtWidgets.QPushButton(self.centralwidget)
        self.button7.setGeometry(QtCore.QRect(0, 50, 70, 60))
        self.button7.setObjectName("button7")
        self.button8 = QtWidgets.QPushButton(self.centralwidget)
        self.button8.setGeometry(QtCore.QRect(70, 50, 70, 60))
        self.button8.setObjectName("button8")
        self.button9 = QtWidgets.QPushButton(self.centralwidget)
        self.button9.setGeometry(QtCore.QRect(140, 50, 70, 60))
        self.button9.setObjectName("button9")
        self.button4 = QtWidgets.QPushButton(self.centralwidget)
        self.button4.setGeometry(QtCore.QRect(0, 110, 70, 60))
        self.button4.setObjectName("button4")
        self.button5 = QtWidgets.QPushButton(self.centralwidget)
        self.button5.setGeometry(QtCore.QRect(70, 110, 70, 60))
        self.button5.setObjectName("button5")
        self.button6 = QtWidgets.QPushButton(self.centralwidget)
        self.button6.setGeometry(QtCore.QRect(140, 110, 70, 60))
        self.button6.setObjectName("button6")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(0, 170, 70, 60))
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(70, 170, 70, 60))
        self.button2.setObjectName("button2")
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(140, 170, 70, 60))
        self.button3.setObjectName("button3")
        self.plus_button = QtWidgets.QPushButton(self.centralwidget)
        self.plus_button.setGeometry(QtCore.QRect(210, 50, 90, 90))
        self.plus_button.setObjectName("plus_button")
        self.minus_button = QtWidgets.QPushButton(self.centralwidget)
        self.minus_button.setGeometry(QtCore.QRect(210, 140, 90, 90))
        self.minus_button.setObjectName("minus_button")
        self.mult_button = QtWidgets.QPushButton(self.centralwidget)
        self.mult_button.setGeometry(QtCore.QRect(0, 230, 140, 90))
        self.mult_button.setObjectName("mult_button")
        self.division_button = QtWidgets.QPushButton(self.centralwidget)
        self.division_button.setGeometry(QtCore.QRect(140, 230, 160, 91))
        self.division_button.setObjectName("division_button")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(250, 0, 50, 50))
        self.button_delete.setObjectName("button_delete")
        self.button_open_brackets = QtWidgets.QPushButton(self.centralwidget)
        self.button_open_brackets.setGeometry(QtCore.QRect(140, 320, 80, 40))
        self.button_open_brackets.setObjectName("button_open_brackets")
        self.button_close_brackets = QtWidgets.QPushButton(self.centralwidget)
        self.button_close_brackets.setGeometry(QtCore.QRect(140, 360, 80, 40))
        self.button_close_brackets.setObjectName("button_close_brackets")
        self.button_dot = QtWidgets.QPushButton(self.centralwidget)
        self.button_dot.setGeometry(QtCore.QRect(80, 320, 60, 80))
        self.button_dot.setObjectName("button_dot")
        self.del_button = QtWidgets.QPushButton(self.centralwidget)
        self.del_button.setGeometry(QtCore.QRect(200, 0, 50, 50))
        self.del_button.setObjectName("del_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label.setText(_translate("MainWindow", "0"))
        self.button0.setText(_translate("MainWindow", "0"))
        self.button_equal.setText(_translate("MainWindow", "="))
        self.button7.setText(_translate("MainWindow", "7"))
        self.button8.setText(_translate("MainWindow", "8"))
        self.button9.setText(_translate("MainWindow", "9"))
        self.button4.setText(_translate("MainWindow", "4"))
        self.button5.setText(_translate("MainWindow", "5"))
        self.button6.setText(_translate("MainWindow", "6"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button2.setText(_translate("MainWindow", "2"))
        self.button3.setText(_translate("MainWindow", "3"))
        self.plus_button.setText(_translate("MainWindow", "+"))
        self.minus_button.setText(_translate("MainWindow", "-"))
        self.mult_button.setText(_translate("MainWindow", "*"))
        self.division_button.setText(_translate("MainWindow", "/"))
        self.button_delete.setText(_translate("MainWindow", "<"))
        self.button_open_brackets.setText(_translate("MainWindow", "("))
        self.button_close_brackets.setText(_translate("MainWindow", ")"))
        self.button_dot.setText(_translate("MainWindow", "."))
        self.del_button.setText(_translate("MainWindow", "del"))