from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 447)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 469, 445))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(201, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.del_button = QtWidgets.QPushButton(self.widget)
        self.del_button.setMinimumSize(QtCore.QSize(60, 50))
        self.del_button.setObjectName("del_button")
        self.gridLayout.addWidget(self.del_button, 0, 4, 1, 3)
        self.button_delete = QtWidgets.QPushButton(self.widget)
        self.button_delete.setMinimumSize(QtCore.QSize(50, 50))
        self.button_delete.setObjectName("button_delete")
        self.gridLayout.addWidget(self.button_delete, 0, 7, 1, 1)
        self.button7 = QtWidgets.QPushButton(self.widget)
        self.button7.setMinimumSize(QtCore.QSize(70, 60))
        self.button7.setObjectName("button7")
        self.gridLayout.addWidget(self.button7, 1, 0, 1, 1)
        self.button8 = QtWidgets.QPushButton(self.widget)
        self.button8.setMinimumSize(QtCore.QSize(70, 60))
        self.button8.setObjectName("button8")
        self.gridLayout.addWidget(self.button8, 1, 1, 1, 2)
        self.button9 = QtWidgets.QPushButton(self.widget)
        self.button9.setMinimumSize(QtCore.QSize(70, 60))
        self.button9.setObjectName("button9")
        self.gridLayout.addWidget(self.button9, 1, 3, 1, 2)
        self.plus_button = QtWidgets.QPushButton(self.widget)
        self.plus_button.setMinimumSize(QtCore.QSize(90, 90))
        self.plus_button.setObjectName("plus_button")
        self.gridLayout.addWidget(self.plus_button, 1, 5, 2, 3)
        self.button4 = QtWidgets.QPushButton(self.widget)
        self.button4.setMinimumSize(QtCore.QSize(70, 60))
        self.button4.setObjectName("button4")
        self.gridLayout.addWidget(self.button4, 2, 0, 2, 1)
        self.button5 = QtWidgets.QPushButton(self.widget)
        self.button5.setMinimumSize(QtCore.QSize(70, 60))
        self.button5.setObjectName("button5")
        self.gridLayout.addWidget(self.button5, 2, 1, 2, 2)
        self.button6 = QtWidgets.QPushButton(self.widget)
        self.button6.setMinimumSize(QtCore.QSize(70, 60))
        self.button6.setObjectName("button6")
        self.gridLayout.addWidget(self.button6, 2, 3, 2, 2)
        self.minus_button = QtWidgets.QPushButton(self.widget)
        self.minus_button.setMinimumSize(QtCore.QSize(90, 90))
        self.minus_button.setObjectName("minus_button")
        self.gridLayout.addWidget(self.minus_button, 3, 5, 2, 3)
        self.button1 = QtWidgets.QPushButton(self.widget)
        self.button1.setMinimumSize(QtCore.QSize(70, 60))
        self.button1.setObjectName("button1")
        self.gridLayout.addWidget(self.button1, 4, 0, 1, 1)
        self.button2 = QtWidgets.QPushButton(self.widget)
        self.button2.setMinimumSize(QtCore.QSize(70, 60))
        self.button2.setObjectName("button2")
        self.gridLayout.addWidget(self.button2, 4, 1, 1, 2)
        self.button3 = QtWidgets.QPushButton(self.widget)
        self.button3.setMinimumSize(QtCore.QSize(70, 60))
        self.button3.setObjectName("button3")
        self.gridLayout.addWidget(self.button3, 4, 3, 1, 2)
        self.mult_button = QtWidgets.QPushButton(self.widget)
        self.mult_button.setMinimumSize(QtCore.QSize(140, 90))
        self.mult_button.setObjectName("mult_button")
        self.gridLayout.addWidget(self.mult_button, 5, 0, 1, 3)
        self.division_button = QtWidgets.QPushButton(self.widget)
        self.division_button.setMinimumSize(QtCore.QSize(160, 91))
        self.division_button.setObjectName("division_button")
        self.gridLayout.addWidget(self.division_button, 5, 3, 1, 5)
        self.button0 = QtWidgets.QPushButton(self.widget)
        self.button0.setMinimumSize(QtCore.QSize(80, 80))
        self.button0.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.button0.setObjectName("button0")
        self.gridLayout.addWidget(self.button0, 6, 0, 2, 2)
        self.button_dot = QtWidgets.QPushButton(self.widget)
        self.button_dot.setMinimumSize(QtCore.QSize(60, 80))
        self.button_dot.setObjectName("button_dot")
        self.gridLayout.addWidget(self.button_dot, 6, 2, 2, 1)
        self.button_open_brackets = QtWidgets.QPushButton(self.widget)
        self.button_open_brackets.setMinimumSize(QtCore.QSize(80, 40))
        self.button_open_brackets.setObjectName("button_open_brackets")
        self.gridLayout.addWidget(self.button_open_brackets, 6, 3, 1, 3)
        self.button_equal = QtWidgets.QPushButton(self.widget)
        self.button_equal.setMinimumSize(QtCore.QSize(80, 80))
        self.button_equal.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.button_equal.setObjectName("button_equal")
        self.gridLayout.addWidget(self.button_equal, 6, 6, 2, 2)
        self.button_close_brackets = QtWidgets.QPushButton(self.widget)
        self.button_close_brackets.setMinimumSize(QtCore.QSize(80, 40))
        self.button_close_brackets.setObjectName("button_close_brackets")
        self.gridLayout.addWidget(self.button_close_brackets, 7, 3, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label.setText(_translate("MainWindow", "0"))
        self.del_button.setText(_translate("MainWindow", "del"))
        self.button_delete.setText(_translate("MainWindow", "<"))
        self.button7.setText(_translate("MainWindow", "7"))
        self.button8.setText(_translate("MainWindow", "8"))
        self.button9.setText(_translate("MainWindow", "9"))
        self.plus_button.setText(_translate("MainWindow", "+"))
        self.button4.setText(_translate("MainWindow", "4"))
        self.button5.setText(_translate("MainWindow", "5"))
        self.button6.setText(_translate("MainWindow", "6"))
        self.minus_button.setText(_translate("MainWindow", "-"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button2.setText(_translate("MainWindow", "2"))
        self.button3.setText(_translate("MainWindow", "3"))
        self.mult_button.setText(_translate("MainWindow", "*"))
        self.division_button.setText(_translate("MainWindow", "/"))
        self.button0.setText(_translate("MainWindow", "0"))
        self.button_dot.setText(_translate("MainWindow", "."))
        self.button_open_brackets.setText(_translate("MainWindow", "("))
        self.button_equal.setText(_translate("MainWindow", "="))
        self.button_close_brackets.setText(_translate("MainWindow", ")"))